### ISSUE TITLE
Internship Request 😃 

### ISSUE THREAD

**Issue by radiumrasheed** [codinger41/treklite-backend#1]
Hi @codinger41 

I see this project as a beautiful one I want to use it as a guide to learning python<Flask>

I intend to build an API only application but as REST and using MongoDB.

I'm coming from a javascript background and hope you'll be chanced to help me out when I hit a snag.

cheers 🍻

**Comment by codinger41** [comment]
Hey, sure @radiumrasheed! Happy to help 👍

**Comment by radiumrasheed** [comment]
thanks 👍

**Comment by radiumrasheed** [comment]
hello @codinger41 
so I've embarked on this project and it's going well. 
But something I can't seem to get is the generic error handler. Since it's an API only app. I don't want it to return any HTML error page. I need it to return JSON no matter what. 
How do I go about it?
